# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en

pl:
  languageCode: pl
  contentDir: content/pl
  menu:
    main:
      - name: Tour
        url: tour
        weight: 10
      - name: News
        url: post
        weight: 20
      - name: Zespół
        url: people
        weight: 30
      - name: Wydarzenia
        url: event
        weight: 40
      - name: Publikacje
        url: publication
        weight: 50
      - name: Kontakt
        url: contact
        weight: 60

nb:
  languageCode: nb
  contentDir: content/nb
  menu:
    main:
      - name: Tour
        url: tour
        weight: 10
      - name: News
        url: post
        weight: 20
      - name: Team
        url: people
        weight: 30
      - name: Hendelser
        url: event
        weight: 40
      - name: Publikasjoner
        url: publication
        weight: 50
      - name: Kontakt
        url: contact
        weight: 60

